apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-secrets
  namespace: fraud-detection
type: Opaque
data:
  # base64-encoded — generate with: echo -n "your_value" | base64
  DB_PASSWORD: cmVwbGFjZV9tZQ==
  API_KEY:     cmVwbGFjZV9tZQ==
  SECRET_KEY:  cmVwbGFjZV9tZQ==